databaseChangeLog:
  - changeSet:
      id: V062_rename_LDAPConfig_to_ldapconfig
      author: seafile
      failOnError: false
      preConditions:
        - tableExists:
            tableName: LDAPConfig
      changes:
        - renameTable:
            oldTableName: LDAPConfig
            newTableName: ldapconfig
  - changeSet:
      id: V062_create_ldapconfig
      author: seafile
      changes:
        - createTable:
            ifNotExists: true
            tableName: ldapconfig
            columns:
              - column:
                  name: id
                  type: int
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: cfg_group
                  type: varchar(255)
                  constraints:
                    nullable: false
              - column:
                  name: cfg_key
                  type: varchar(255)
                  constraints:
                    nullable: false
              - column:
                  name: value
                  type: varchar(255)
              - column:
                  name: property
                  type: int