ALTER TABLE `UserQuota` 
  DROP PRIMARY KEY,
  ADD COLUMN `id` bigint NOT NULL AUTO_INCREMENT FIRST,
  ADD PRIMARY KEY (`id`),
  MODIFY `user` varchar(255) DEFAULT NULL,
  ADD UNIQUE KEY `user` (`user`);
