ALTER TABLE WebAP
DROP CONSTRAINT webap_pkey;
ALTER TABLE WebAP
    ADD COLUMN id serial NOT NULL;
ALTER TABLE ONLY WebAP
    ADD CONSTRAINT WebAP_id_pkey PRIMARY KEY (id);
CREATE UNIQUE INDEX WebAP_repo_id ON WebAP USING btree (repo_id);
