name: Database Migration Tests

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:10.11
        env:
          MARIADB_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="healthcheck.sh --connect --innodb_initialized" --health-interval=10s --health-timeout=5s --health-retries=3

      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make mariadb-client postgresql-client

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'

      - uses: liquibase/setup-liquibase@v2
        with:
          version: '4.33.0'
          edition: 'oss'

      - name: Run Tests
        working-directory: test
        run: make

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: migration-reports
          path: test/reports/*.txt
